<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
      <UpToDateCheckInput Remove="Areas\MyFeature\Pages\Page1.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CSharpFunctionalExtensions" Version="3.7.0" />
      <PackageReference Include="EF.Core.Repositories" Version="1.2.2" />
      <PackageReference Include="MediatR" Version="14.2.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\FixCompany.Data\FixCompany.Data.csproj" />
      <ProjectReference Include="..\FixCompany.Entity.Domain\FixCompany.Entity.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="dto\" />
    </ItemGroup>


</Project>
