// <auto-generated />
using FixCompany.Data.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FixCompany.Data.Migrations
{
    [DbContext(typeof(FixCompanyContext))]
    [Migration("20260901193555_addInitData")]
    partial class addInitData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FixCompany.Entity.Domain.models.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("FixCompany.Entity.Domain.models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Мастер"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Клиент"
                        });
                });

            modelBuilder.Entity("FixCompany.Entity.Domain.models.Entity", b =>
                {
                    b.HasOne("FixCompany.Entity.Domain.models.Role", "Role")
                        .WithMany("Entitis")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FixCompany.Entity.Domain.models.Role", b =>
                {
                    b.Navigation("Entitis");
                });
#pragma warning restore 612, 618
        }
    }
}
