<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
      <UpToDateCheckInput Remove="Areas\MyFeature\Pages\Page1.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="14.2.0" />
      <PackageReference Include="MudBlazor" Version="9.9.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\FixCompany.Entity.Command\FixCompany.Entity.Command.csproj" />
      <ProjectReference Include="..\FixCompany.Entity.Domain\FixCompany.Entity.Domain.csproj" />
    </ItemGroup>


</Project>
